Add support for installing additional packages
Clean up docker output.
Closes #672
Closes #640

diff --git a/src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template b/src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template
--- a/src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template
+++ b/src/Azure.Functions.Cli/StaticResources/python_docker_build.sh.template
@@ -1,5 +1,8 @@
 ﻿#! /bin/bash
 
+# Exit on errors
+set -e
+
 cd /home/site/wwwroot
 if [ -d worker_venv ]; then
     rm -rf worker_venv
